plugins:
  - react-hooks
env:
  browser: true
  commonjs: true
  es2017: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:prettier/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
  sourceType: module
rules:
  'react-hooks/rules-of-hooks':
    - error
  'react-hooks/exhaustive-deps':
    - warn
